//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace server
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class db : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new db object using the connection string found in the 'db' section of the application configuration file.
        /// </summary>
        public db() : base("name=db", "db")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db object.
        /// </summary>
        public db(string connectionString) : base(connectionString, "db")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db object.
        /// </summary>
        public db(EntityConnection connection) : base(connection, "db")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="categ">No Metadata Documentation available.</param>
        /// <param name="diff">No Metadata Documentation available.</param>
        public ObjectResult<global::System.String> select_word(global::System.String categ, global::System.String diff)
        {
            ObjectParameter categParameter;
            if (categ != null)
            {
                categParameter = new ObjectParameter("categ", categ);
            }
            else
            {
                categParameter = new ObjectParameter("categ", typeof(global::System.String));
            }
    
            ObjectParameter diffParameter;
            if (diff != null)
            {
                diffParameter = new ObjectParameter("diff", diff);
            }
            else
            {
                diffParameter = new ObjectParameter("diff", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<global::System.String>("select_word", categParameter, diffParameter);
        }

        #endregion

    }

    #endregion

}
